language: node_js

node_js:
  - 0.10

before_script:
  - npm -q install
  - npm -q install -g testem coffee-script
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - ./testem -l PhantomJS
